# This file is for OSD-GCP RBAC installation only.
# It is applied by `helm upgrade` after the `values-showcase-rbac.yaml` is applied and only contains complementary differences for OSD-GCP.
# Note, that it overwrites the whole key that is present in this file.
# The only exception is global.dynamic.plugins, that gets merged with the base file.

# Disable orchestrator for OSD-GCP due to infrastructure limitations
orchestrator: null

global:
  dynamic:
    plugins:
      # Disable orchestrator plugins for OSD-GCP
      - package: 'oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/red-hat-developer-hub-backstage-plugin-orchestrator:{{ "{{" }}inherit{{ "}}" }}'
        disabled: true
      - package: 'oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/red-hat-developer-hub-backstage-plugin-orchestrator-backend:{{ "{{" }}inherit{{ "}}" }}'
        disabled: true
      - package: 'oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/red-hat-developer-hub-backstage-plugin-scaffolder-backend-module-orchestrator:{{ "{{" }}inherit{{ "}}" }}'
        disabled: true
      - package: 'oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/red-hat-developer-hub-backstage-plugin-orchestrator-form-widgets:{{ "{{" }}inherit{{ "}}" }}'
        disabled: true
