kind: Secret
apiVersion: v1
metadata:
  name: postgres-cred
data:
  POSTGRES_PASSWORD: NHN5eD1wPGpxUW4uczFpVlMtKSg5KU8v
  POSTGRES_PORT: NTQzMg==
  POSTGRES_USER: amFudXMtaWRw
  POSTGRES_HOST: cG9zdGdyZXNzLWV4dGVybmFsLWRiLXByaW1hcnkucG9zdGdyZXNzLWV4dGVybmFsLWRiLnN2Yy5jbHVzdGVyLmxvY2Fs
  PGSSLMODE: cmVxdWlyZQ==
  NODE_EXTRA_CA_CERTS: L29wdC9hcHAtcm9vdC9zcmMvcG9zdGdyZXMtY3J0LnBlbQ==
  RHDH_RUNTIME_URL: dG1w
